# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc413918927495ba51a5aa1a095c43a97960fe202bef06b865a4fd705c9348e151972ec065d8d8ff3d5d6d8d37d080de8dab01c0b90a31e94f025b4550cf1524

test:
  secret_key_base: dfc22a5f92fa98153af5a0801562a7203e65d42f57e045c9606b9143c9c7dda6d5d2fc14d849fe2ace36f042e3430edeb56e03f3758c9dc2c86c424f8ebeb98d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
